version: '3.7'
services:
  Elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=tribi-auditor
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - elk

  Elasticsearch_exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.5.0
    container_name: es_exporter
    command:
     - --es.uri=http://elastic:vGb3nxDaoiITFrOra7dV3PE3UK6Ws0pH@elasticsearch:9200
     - --es.all
    restart: always
    ports:
      - 9114:9114
    networks:
      - elk

  Logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - /var/log/:/var/log:ro
    command: logstash -f /usr/share/logstash/pipeline
    depends_on:
      - Elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  Kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    depends_on:
      - Elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local

    ===========================
    # Logstash configuration file yg fix
    Logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /var/log/:/var/log:ro
    command: logstash -f /usr/share/logstash/config
    depends_on:
      - Elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m --illegal-access=warn"
    networks:
      - elk
    =============================