apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: noval
  labels:
    app: postgres
data:
  POSTGRES_DB: mydb
  POSTGRES_USER: martha
  pg_hba.conf: |
    # PostgreSQL Client Authentication Configuration File
    # ===================================================
    # IPv4 local connections:
    local all all trust
    host mydb martha 0.0.0.0/0 trust