apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tribi
  name: python-deployment
  labels:
    app: python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-deployment
  template:
   metadata:
     labels:
       app: python-deployment
   spec:
    containers:
    - name: python-deployment
      image: hanifahmrt/app.python:3.9.2
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      securityContext:
        runAsUser: 0
      resources:
        requests:
          memory: "64Mi"
          cpu: "150m"
