apiVersion: v1
kind: Service
metadata:
  namespace: miniostorage
  name: minio-service
  labels:
    app: minio
spec: 
  type: LoadBalancer
  ports:
  - port: 9090
    name: http-minio
  - port: 9000
    name: s3-minio
  selector:
    app: minio
