apiVersion: v1
kind: Service
metadata:
  namespace: tribi
  name: service
  labels:
    app: service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
  selector:
    app: myapp-deployment


